# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.s3_load_balancer_groups_api import S3LoadBalancerGroupsApi  # noqa: E501
from xms_client.rest import ApiException


class TestS3LoadBalancerGroupsApi(unittest.TestCase):
    """S3LoadBalancerGroupsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.s3_load_balancer_groups_api.S3LoadBalancerGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_s3_load_balancers_to_group(self):
        """Test case for add_s3_load_balancers_to_group

        """
        pass

    def test_create_s3_load_balancer_group(self):
        """Test case for create_s3_load_balancer_group

        """
        pass

    def test_delete_s3_load_balancer_group(self):
        """Test case for delete_s3_load_balancer_group

        """
        pass

    def test_get_s3_load_balancer_group(self):
        """Test case for get_s3_load_balancer_group

        """
        pass

    def test_list_s3_load_balancer_groups(self):
        """Test case for list_s3_load_balancer_groups

        """
        pass

    def test_redeploy_s3_load_balancer_group(self):
        """Test case for redeploy_s3_load_balancer_group

        """
        pass

    def test_remove_s3_load_balancers_from_group(self):
        """Test case for remove_s3_load_balancers_from_group

        """
        pass

    def test_update_s3_load_balancer_group(self):
        """Test case for update_s3_load_balancer_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
