# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.dfs_quotas_api import DfsQuotasApi  # noqa: E501
from xms_client.rest import ApiException


class TestDfsQuotasApi(unittest.TestCase):
    """DfsQuotasApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.dfs_quotas_api.DfsQuotasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_dfs_quota(self):
        """Test case for create_dfs_quota

        """
        pass

    def test_delete_dfs_quota(self):
        """Test case for delete_dfs_quota

        """
        pass

    def test_dfs_quota_overview(self):
        """Test case for dfs_quota_overview

        """
        pass

    def test_get_dfs_quota(self):
        """Test case for get_dfs_quota

        """
        pass

    def test_get_dfs_quota_predictions(self):
        """Test case for get_dfs_quota_predictions

        """
        pass

    def test_get_dfs_quota_samples(self):
        """Test case for get_dfs_quota_samples

        """
        pass

    def test_list_dfs_quotas(self):
        """Test case for list_dfs_quotas

        """
        pass

    def test_path_validator(self):
        """Test case for path_validator

        """
        pass

    def test_update_dfs_quota(self):
        """Test case for update_dfs_quota

        """
        pass


if __name__ == '__main__':
    unittest.main()
