# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.network_diagnoses_api import NetworkDiagnosesApi  # noqa: E501
from xms_client.rest import ApiException


class TestNetworkDiagnosesApi(unittest.TestCase):
    """NetworkDiagnosesApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.network_diagnoses_api.NetworkDiagnosesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_network_diagnosis(self):
        """Test case for create_network_diagnosis

        """
        pass

    def test_delete_network_diagnosis(self):
        """Test case for delete_network_diagnosis

        """
        pass

    def test_get_network_diagnosis(self):
        """Test case for get_network_diagnosis

        """
        pass

    def test_list_network_diagnoses(self):
        """Test case for list_network_diagnoses

        """
        pass

    def test_stop_network_diagnosis(self):
        """Test case for stop_network_diagnosis

        """
        pass


if __name__ == '__main__':
    unittest.main()
