# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.vip_groups_api import VipGroupsApi  # noqa: E501
from xms_client.rest import ApiException


class TestVipGroupsApi(unittest.TestCase):
    """VipGroupsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.vip_groups_api.VipGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_vip_group(self):
        """Test case for create_vip_group

        """
        pass

    def test_delete_vip_group(self):
        """Test case for delete_vip_group

        """
        pass

    def test_get_vip_group(self):
        """Test case for get_vip_group

        """
        pass

    def test_list_vip_groups(self):
        """Test case for list_vip_groups

        """
        pass

    def test_redeploy_vip_group(self):
        """Test case for redeploy_vip_group

        """
        pass

    def test_update_vip_group(self):
        """Test case for update_vip_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
