# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.consistent_snapshot import ConsistentSnapshot  # noqa: E501
from xms_client.rest import ApiException


class TestConsistentSnapshot(unittest.TestCase):
    """ConsistentSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsistentSnapshot(self):
        """Test ConsistentSnapshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.consistent_snapshot.ConsistentSnapshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
