# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.dp_fs_snapshot_jobs_api import DpFsSnapshotJobsApi  # noqa: E501
from xms_client.rest import ApiException


class TestDpFsSnapshotJobsApi(unittest.TestCase):
    """DpFsSnapshotJobsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.dp_fs_snapshot_jobs_api.DpFsSnapshotJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_dp_fs_snapshot_job(self):
        """Test case for get_dp_fs_snapshot_job

        """
        pass

    def test_list_dp_fs_snapshot_jobs(self):
        """Test case for list_dp_fs_snapshot_jobs

        """
        pass


if __name__ == '__main__':
    unittest.main()
