# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.dfs_nfs_shares_api import DfsNfsSharesApi  # noqa: E501
from xms_client.rest import ApiException


class TestDfsNfsSharesApi(unittest.TestCase):
    """DfsNfsSharesApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.dfs_nfs_shares_api.DfsNfsSharesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_dfs_nfs_share_ac_ls(self):
        """Test case for add_dfs_nfs_share_ac_ls

        """
        pass

    def test_create_dfs_nfs_share(self):
        """Test case for create_dfs_nfs_share

        """
        pass

    def test_delete_dfs_nfs_share(self):
        """Test case for delete_dfs_nfs_share

        """
        pass

    def test_get_dfs_nfs_share(self):
        """Test case for get_dfs_nfs_share

        """
        pass

    def test_list_dfs_nfs_shares(self):
        """Test case for list_dfs_nfs_shares

        """
        pass

    def test_remove_dfs_nfs_share_ac_ls(self):
        """Test case for remove_dfs_nfs_share_ac_ls

        """
        pass

    def test_update_dfs_nfs_share_ac_ls(self):
        """Test case for update_dfs_nfs_share_ac_ls

        """
        pass


if __name__ == '__main__':
    unittest.main()
