# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.os_builtin_blu_rays_api import OsBuiltinBluRaysApi  # noqa: E501
from xms_client.rest import ApiException


class TestOsBuiltinBluRaysApi(unittest.TestCase):
    """OsBuiltinBluRaysApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.os_builtin_blu_rays_api.OsBuiltinBluRaysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_os_builtin_blu_ray(self):
        """Test case for create_os_builtin_blu_ray

        """
        pass

    def test_delete_os_builtin_blu_ray(self):
        """Test case for delete_os_builtin_blu_ray

        """
        pass

    def test_get_os_builtin_blu_ray(self):
        """Test case for get_os_builtin_blu_ray

        """
        pass

    def test_list_os_builtin_blu_rays(self):
        """Test case for list_os_builtin_blu_rays

        """
        pass

    def test_update_os_builtin_blu_ray(self):
        """Test case for update_os_builtin_blu_ray

        """
        pass


if __name__ == '__main__':
    unittest.main()
