# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.vm_flavors_api import VmFlavorsApi  # noqa: E501
from xms_client.rest import ApiException


class TestVmFlavorsApi(unittest.TestCase):
    """VmFlavorsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.vm_flavors_api.VmFlavorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_vm_flavor(self):
        """Test case for get_vm_flavor

        """
        pass

    def test_list_vm_flavors(self):
        """Test case for list_vm_flavors

        """
        pass


if __name__ == '__main__':
    unittest.main()
