# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.dfs_s3_keys_api import DfsS3KeysApi  # noqa: E501
from xms_client.rest import ApiException


class TestDfsS3KeysApi(unittest.TestCase):
    """DfsS3KeysApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.dfs_s3_keys_api.DfsS3KeysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_dfs_s3_key(self):
        """Test case for create_dfs_s3_key

        """
        pass

    def test_delete_dfs_s3_key(self):
        """Test case for delete_dfs_s3_key

        """
        pass

    def test_get_dfs_s3_key(self):
        """Test case for get_dfs_s3_key

        """
        pass

    def test_list_dfs_s3_keys(self):
        """Test case for list_dfs_s3_keys

        """
        pass

    def test_update_dfs_s3_key(self):
        """Test case for update_dfs_s3_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
