# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.api.dp_dfs_snapshots_api import DpDfsSnapshotsApi  # noqa: E501
from xms_client.rest import ApiException


class TestDpDfsSnapshotsApi(unittest.TestCase):
    """DpDfsSnapshotsApi unit test stubs"""

    def setUp(self):
        self.api = xms_client.api.dp_dfs_snapshots_api.DpDfsSnapshotsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_dp_dfs_snapshot(self):
        """Test case for create_dp_dfs_snapshot

        """
        pass

    def test_delete_dp_dfs_snapshot(self):
        """Test case for delete_dp_dfs_snapshot

        """
        pass

    def test_get_dp_dfs_snapshot(self):
        """Test case for get_dp_dfs_snapshot

        """
        pass

    def test_list_dp_dfs_snapshots(self):
        """Test case for list_dp_dfs_snapshots

        """
        pass

    def test_list_dp_dfs_snapshots_by_dfs_path_name(self):
        """Test case for list_dp_dfs_snapshots_by_dfs_path_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
