# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import xms_client
from xms_client.models.os_bucket_custom_labels_remove_req import OSBucketCustomLabelsRemoveReq  # noqa: E501
from xms_client.rest import ApiException


class TestOSBucketCustomLabelsRemoveReq(unittest.TestCase):
    """OSBucketCustomLabelsRemoveReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOSBucketCustomLabelsRemoveReq(self):
        """Test OSBucketCustomLabelsRemoveReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xms_client.models.os_bucket_custom_labels_remove_req.OSBucketCustomLabelsRemoveReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
