# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from xms_client.models.dfs_nfs_share_acl_req import DfsNFSShareACLReq  # noqa: F401,E501


class DfsNFSShareCreateReqShare(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dfs_nfs_share_acls': 'list[DfsNFSShareACLReq]',
        'dfs_rootfs_id': 'int',
        'name': 'str',
        'path': 'str'
    }

    attribute_map = {
        'dfs_nfs_share_acls': 'dfs_nfs_share_acls',
        'dfs_rootfs_id': 'dfs_rootfs_id',
        'name': 'name',
        'path': 'path'
    }

    def __init__(self, dfs_nfs_share_acls=None, dfs_rootfs_id=None, name=None, path=None):  # noqa: E501
        """DfsNFSShareCreateReqShare - a model defined in Swagger"""  # noqa: E501

        self._dfs_nfs_share_acls = None
        self._dfs_rootfs_id = None
        self._name = None
        self._path = None
        self.discriminator = None

        if dfs_nfs_share_acls is not None:
            self.dfs_nfs_share_acls = dfs_nfs_share_acls
        self.dfs_rootfs_id = dfs_rootfs_id
        self.name = name
        self.path = path

    @property
    def dfs_nfs_share_acls(self):
        """Gets the dfs_nfs_share_acls of this DfsNFSShareCreateReqShare.  # noqa: E501

        access control array  # noqa: E501

        :return: The dfs_nfs_share_acls of this DfsNFSShareCreateReqShare.  # noqa: E501
        :rtype: list[DfsNFSShareACLReq]
        """
        return self._dfs_nfs_share_acls

    @dfs_nfs_share_acls.setter
    def dfs_nfs_share_acls(self, dfs_nfs_share_acls):
        """Sets the dfs_nfs_share_acls of this DfsNFSShareCreateReqShare.

        access control array  # noqa: E501

        :param dfs_nfs_share_acls: The dfs_nfs_share_acls of this DfsNFSShareCreateReqShare.  # noqa: E501
        :type: list[DfsNFSShareACLReq]
        """

        self._dfs_nfs_share_acls = dfs_nfs_share_acls

    @property
    def dfs_rootfs_id(self):
        """Gets the dfs_rootfs_id of this DfsNFSShareCreateReqShare.  # noqa: E501

        rootfs id  # noqa: E501

        :return: The dfs_rootfs_id of this DfsNFSShareCreateReqShare.  # noqa: E501
        :rtype: int
        """
        return self._dfs_rootfs_id

    @dfs_rootfs_id.setter
    def dfs_rootfs_id(self, dfs_rootfs_id):
        """Sets the dfs_rootfs_id of this DfsNFSShareCreateReqShare.

        rootfs id  # noqa: E501

        :param dfs_rootfs_id: The dfs_rootfs_id of this DfsNFSShareCreateReqShare.  # noqa: E501
        :type: int
        """
        if dfs_rootfs_id is None:
            raise ValueError("Invalid value for `dfs_rootfs_id`, must not be `None`")  # noqa: E501

        self._dfs_rootfs_id = dfs_rootfs_id

    @property
    def name(self):
        """Gets the name of this DfsNFSShareCreateReqShare.  # noqa: E501

        name of share  # noqa: E501

        :return: The name of this DfsNFSShareCreateReqShare.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DfsNFSShareCreateReqShare.

        name of share  # noqa: E501

        :param name: The name of this DfsNFSShareCreateReqShare.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def path(self):
        """Gets the path of this DfsNFSShareCreateReqShare.  # noqa: E501

        diectrory path  # noqa: E501

        :return: The path of this DfsNFSShareCreateReqShare.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this DfsNFSShareCreateReqShare.

        diectrory path  # noqa: E501

        :param path: The path of this DfsNFSShareCreateReqShare.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DfsNFSShareCreateReqShare):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
