# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from xms_client.models.dns_load_balance_policy_nestview import DNSLoadBalancePolicyNestview  # noqa: F401,E501
# from xms_client.models.dns_zone import DNSZone  # noqa: F401,E501


class DNSDomainName(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create': 'datetime',
        'dns_load_balance_policy': 'DNSLoadBalancePolicyNestview',
        'dns_zone': 'DNSZone',
        'id': 'int',
        'name': 'str',
        'resource_id': 'int',
        'resource_type': 'str',
        'status': 'str',
        'update': 'datetime'
    }

    attribute_map = {
        'create': 'create',
        'dns_load_balance_policy': 'dns_load_balance_policy',
        'dns_zone': 'dns_zone',
        'id': 'id',
        'name': 'name',
        'resource_id': 'resource_id',
        'resource_type': 'resource_type',
        'status': 'status',
        'update': 'update'
    }

    def __init__(self, create=None, dns_load_balance_policy=None, dns_zone=None, id=None, name=None, resource_id=None, resource_type=None, status=None, update=None):  # noqa: E501
        """DNSDomainName - a model defined in Swagger"""  # noqa: E501

        self._create = None
        self._dns_load_balance_policy = None
        self._dns_zone = None
        self._id = None
        self._name = None
        self._resource_id = None
        self._resource_type = None
        self._status = None
        self._update = None
        self.discriminator = None

        if create is not None:
            self.create = create
        if dns_load_balance_policy is not None:
            self.dns_load_balance_policy = dns_load_balance_policy
        if dns_zone is not None:
            self.dns_zone = dns_zone
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if resource_id is not None:
            self.resource_id = resource_id
        if resource_type is not None:
            self.resource_type = resource_type
        if status is not None:
            self.status = status
        if update is not None:
            self.update = update

    @property
    def create(self):
        """Gets the create of this DNSDomainName.  # noqa: E501


        :return: The create of this DNSDomainName.  # noqa: E501
        :rtype: datetime
        """
        return self._create

    @create.setter
    def create(self, create):
        """Sets the create of this DNSDomainName.


        :param create: The create of this DNSDomainName.  # noqa: E501
        :type: datetime
        """

        self._create = create

    @property
    def dns_load_balance_policy(self):
        """Gets the dns_load_balance_policy of this DNSDomainName.  # noqa: E501


        :return: The dns_load_balance_policy of this DNSDomainName.  # noqa: E501
        :rtype: DNSLoadBalancePolicyNestview
        """
        return self._dns_load_balance_policy

    @dns_load_balance_policy.setter
    def dns_load_balance_policy(self, dns_load_balance_policy):
        """Sets the dns_load_balance_policy of this DNSDomainName.


        :param dns_load_balance_policy: The dns_load_balance_policy of this DNSDomainName.  # noqa: E501
        :type: DNSLoadBalancePolicyNestview
        """

        self._dns_load_balance_policy = dns_load_balance_policy

    @property
    def dns_zone(self):
        """Gets the dns_zone of this DNSDomainName.  # noqa: E501


        :return: The dns_zone of this DNSDomainName.  # noqa: E501
        :rtype: DNSZone
        """
        return self._dns_zone

    @dns_zone.setter
    def dns_zone(self, dns_zone):
        """Sets the dns_zone of this DNSDomainName.


        :param dns_zone: The dns_zone of this DNSDomainName.  # noqa: E501
        :type: DNSZone
        """

        self._dns_zone = dns_zone

    @property
    def id(self):
        """Gets the id of this DNSDomainName.  # noqa: E501


        :return: The id of this DNSDomainName.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DNSDomainName.


        :param id: The id of this DNSDomainName.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this DNSDomainName.  # noqa: E501


        :return: The name of this DNSDomainName.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DNSDomainName.


        :param name: The name of this DNSDomainName.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def resource_id(self):
        """Gets the resource_id of this DNSDomainName.  # noqa: E501


        :return: The resource_id of this DNSDomainName.  # noqa: E501
        :rtype: int
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this DNSDomainName.


        :param resource_id: The resource_id of this DNSDomainName.  # noqa: E501
        :type: int
        """

        self._resource_id = resource_id

    @property
    def resource_type(self):
        """Gets the resource_type of this DNSDomainName.  # noqa: E501


        :return: The resource_type of this DNSDomainName.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this DNSDomainName.


        :param resource_type: The resource_type of this DNSDomainName.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def status(self):
        """Gets the status of this DNSDomainName.  # noqa: E501


        :return: The status of this DNSDomainName.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DNSDomainName.


        :param status: The status of this DNSDomainName.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def update(self):
        """Gets the update of this DNSDomainName.  # noqa: E501


        :return: The update of this DNSDomainName.  # noqa: E501
        :rtype: datetime
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this DNSDomainName.


        :param update: The update of this DNSDomainName.  # noqa: E501
        :type: datetime
        """

        self._update = update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DNSDomainName):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
