# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class LoginSSOExtra(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'state': 'str',
        'ticket': 'str'
    }

    attribute_map = {
        'code': 'code',
        'state': 'state',
        'ticket': 'ticket'
    }

    def __init__(self, code=None, state=None, ticket=None):  # noqa: E501
        """LoginSSOExtra - a model defined in Swagger"""  # noqa: E501

        self._code = None
        self._state = None
        self._ticket = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if state is not None:
            self.state = state
        if ticket is not None:
            self.ticket = ticket

    @property
    def code(self):
        """Gets the code of this LoginSSOExtra.  # noqa: E501


        :return: The code of this LoginSSOExtra.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this LoginSSOExtra.


        :param code: The code of this LoginSSOExtra.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def state(self):
        """Gets the state of this LoginSSOExtra.  # noqa: E501


        :return: The state of this LoginSSOExtra.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this LoginSSOExtra.


        :param state: The state of this LoginSSOExtra.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def ticket(self):
        """Gets the ticket of this LoginSSOExtra.  # noqa: E501


        :return: The ticket of this LoginSSOExtra.  # noqa: E501
        :rtype: str
        """
        return self._ticket

    @ticket.setter
    def ticket(self, ticket):
        """Sets the ticket of this LoginSSOExtra.


        :param ticket: The ticket of this LoginSSOExtra.  # noqa: E501
        :type: str
        """

        self._ticket = ticket

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoginSSOExtra):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
