# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class OSBuiltinBluRayCreateReqBuiltinBluRay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'admin_endpoint': 'str',
        'name': 'str',
        'password': 'str',
        'user_name': 'str'
    }

    attribute_map = {
        'admin_endpoint': 'admin_endpoint',
        'name': 'name',
        'password': 'password',
        'user_name': 'user_name'
    }

    def __init__(self, admin_endpoint=None, name=None, password=None, user_name=None):  # noqa: E501
        """OSBuiltinBluRayCreateReqBuiltinBluRay - a model defined in Swagger"""  # noqa: E501

        self._admin_endpoint = None
        self._name = None
        self._password = None
        self._user_name = None
        self.discriminator = None

        self.admin_endpoint = admin_endpoint
        self.name = name
        self.password = password
        self.user_name = user_name

    @property
    def admin_endpoint(self):
        """Gets the admin_endpoint of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501


        :return: The admin_endpoint of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :rtype: str
        """
        return self._admin_endpoint

    @admin_endpoint.setter
    def admin_endpoint(self, admin_endpoint):
        """Sets the admin_endpoint of this OSBuiltinBluRayCreateReqBuiltinBluRay.


        :param admin_endpoint: The admin_endpoint of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :type: str
        """
        if admin_endpoint is None:
            raise ValueError("Invalid value for `admin_endpoint`, must not be `None`")  # noqa: E501

        self._admin_endpoint = admin_endpoint

    @property
    def name(self):
        """Gets the name of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501


        :return: The name of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OSBuiltinBluRayCreateReqBuiltinBluRay.


        :param name: The name of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def password(self):
        """Gets the password of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501


        :return: The password of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this OSBuiltinBluRayCreateReqBuiltinBluRay.


        :param password: The password of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def user_name(self):
        """Gets the user_name of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501


        :return: The user_name of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this OSBuiltinBluRayCreateReqBuiltinBluRay.


        :param user_name: The user_name of this OSBuiltinBluRayCreateReqBuiltinBluRay.  # noqa: E501
        :type: str
        """
        if user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

        self._user_name = user_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OSBuiltinBluRayCreateReqBuiltinBluRay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
