# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class OsdGroupNestview(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'numa_enabled': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'numa_enabled': 'numa_enabled'
    }

    def __init__(self, id=None, numa_enabled=None):  # noqa: E501
        """OsdGroupNestview - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._numa_enabled = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if numa_enabled is not None:
            self.numa_enabled = numa_enabled

    @property
    def id(self):
        """Gets the id of this OsdGroupNestview.  # noqa: E501


        :return: The id of this OsdGroupNestview.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OsdGroupNestview.


        :param id: The id of this OsdGroupNestview.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def numa_enabled(self):
        """Gets the numa_enabled of this OsdGroupNestview.  # noqa: E501


        :return: The numa_enabled of this OsdGroupNestview.  # noqa: E501
        :rtype: bool
        """
        return self._numa_enabled

    @numa_enabled.setter
    def numa_enabled(self, numa_enabled):
        """Sets the numa_enabled of this OsdGroupNestview.


        :param numa_enabled: The numa_enabled of this OsdGroupNestview.  # noqa: E501
        :type: bool
        """

        self._numa_enabled = numa_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OsdGroupNestview):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
