# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class ProgressInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'str',
        'create': 'datetime',
        'current_progress': 'float',
        'data': 'str',
        'fail_num': 'int',
        'id': 'int',
        'success_num': 'int',
        'total_num': 'int',
        'total_progress': 'float',
        'update': 'datetime'
    }

    attribute_map = {
        'action': 'action',
        'create': 'create',
        'current_progress': 'current_progress',
        'data': 'data',
        'fail_num': 'fail_num',
        'id': 'id',
        'success_num': 'success_num',
        'total_num': 'total_num',
        'total_progress': 'total_progress',
        'update': 'update'
    }

    def __init__(self, action=None, create=None, current_progress=None, data=None, fail_num=None, id=None, success_num=None, total_num=None, total_progress=None, update=None):  # noqa: E501
        """ProgressInfo - a model defined in Swagger"""  # noqa: E501

        self._action = None
        self._create = None
        self._current_progress = None
        self._data = None
        self._fail_num = None
        self._id = None
        self._success_num = None
        self._total_num = None
        self._total_progress = None
        self._update = None
        self.discriminator = None

        if action is not None:
            self.action = action
        if create is not None:
            self.create = create
        if current_progress is not None:
            self.current_progress = current_progress
        if data is not None:
            self.data = data
        if fail_num is not None:
            self.fail_num = fail_num
        if id is not None:
            self.id = id
        if success_num is not None:
            self.success_num = success_num
        if total_num is not None:
            self.total_num = total_num
        if total_progress is not None:
            self.total_progress = total_progress
        if update is not None:
            self.update = update

    @property
    def action(self):
        """Gets the action of this ProgressInfo.  # noqa: E501


        :return: The action of this ProgressInfo.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this ProgressInfo.


        :param action: The action of this ProgressInfo.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def create(self):
        """Gets the create of this ProgressInfo.  # noqa: E501


        :return: The create of this ProgressInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._create

    @create.setter
    def create(self, create):
        """Sets the create of this ProgressInfo.


        :param create: The create of this ProgressInfo.  # noqa: E501
        :type: datetime
        """

        self._create = create

    @property
    def current_progress(self):
        """Gets the current_progress of this ProgressInfo.  # noqa: E501


        :return: The current_progress of this ProgressInfo.  # noqa: E501
        :rtype: float
        """
        return self._current_progress

    @current_progress.setter
    def current_progress(self, current_progress):
        """Sets the current_progress of this ProgressInfo.


        :param current_progress: The current_progress of this ProgressInfo.  # noqa: E501
        :type: float
        """

        self._current_progress = current_progress

    @property
    def data(self):
        """Gets the data of this ProgressInfo.  # noqa: E501


        :return: The data of this ProgressInfo.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ProgressInfo.


        :param data: The data of this ProgressInfo.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def fail_num(self):
        """Gets the fail_num of this ProgressInfo.  # noqa: E501


        :return: The fail_num of this ProgressInfo.  # noqa: E501
        :rtype: int
        """
        return self._fail_num

    @fail_num.setter
    def fail_num(self, fail_num):
        """Sets the fail_num of this ProgressInfo.


        :param fail_num: The fail_num of this ProgressInfo.  # noqa: E501
        :type: int
        """

        self._fail_num = fail_num

    @property
    def id(self):
        """Gets the id of this ProgressInfo.  # noqa: E501


        :return: The id of this ProgressInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProgressInfo.


        :param id: The id of this ProgressInfo.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def success_num(self):
        """Gets the success_num of this ProgressInfo.  # noqa: E501


        :return: The success_num of this ProgressInfo.  # noqa: E501
        :rtype: int
        """
        return self._success_num

    @success_num.setter
    def success_num(self, success_num):
        """Sets the success_num of this ProgressInfo.


        :param success_num: The success_num of this ProgressInfo.  # noqa: E501
        :type: int
        """

        self._success_num = success_num

    @property
    def total_num(self):
        """Gets the total_num of this ProgressInfo.  # noqa: E501


        :return: The total_num of this ProgressInfo.  # noqa: E501
        :rtype: int
        """
        return self._total_num

    @total_num.setter
    def total_num(self, total_num):
        """Sets the total_num of this ProgressInfo.


        :param total_num: The total_num of this ProgressInfo.  # noqa: E501
        :type: int
        """

        self._total_num = total_num

    @property
    def total_progress(self):
        """Gets the total_progress of this ProgressInfo.  # noqa: E501


        :return: The total_progress of this ProgressInfo.  # noqa: E501
        :rtype: float
        """
        return self._total_progress

    @total_progress.setter
    def total_progress(self, total_progress):
        """Sets the total_progress of this ProgressInfo.


        :param total_progress: The total_progress of this ProgressInfo.  # noqa: E501
        :type: float
        """

        self._total_progress = total_progress

    @property
    def update(self):
        """Gets the update of this ProgressInfo.  # noqa: E501


        :return: The update of this ProgressInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this ProgressInfo.


        :param update: The update of this ProgressInfo.  # noqa: E501
        :type: datetime
        """

        self._update = update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProgressInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
