# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: XSCALEROS_5.2.100.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from xms_client.models.volume_stat import VolumeStat  # noqa: F401,E501


class UpdateVolumeStatReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pool_name': 'str',
        'stat': 'VolumeStat',
        'volume_name': 'str'
    }

    attribute_map = {
        'pool_name': 'pool_name',
        'stat': 'stat',
        'volume_name': 'volume_name'
    }

    def __init__(self, pool_name=None, stat=None, volume_name=None):  # noqa: E501
        """UpdateVolumeStatReq - a model defined in Swagger"""  # noqa: E501

        self._pool_name = None
        self._stat = None
        self._volume_name = None
        self.discriminator = None

        if pool_name is not None:
            self.pool_name = pool_name
        if stat is not None:
            self.stat = stat
        if volume_name is not None:
            self.volume_name = volume_name

    @property
    def pool_name(self):
        """Gets the pool_name of this UpdateVolumeStatReq.  # noqa: E501


        :return: The pool_name of this UpdateVolumeStatReq.  # noqa: E501
        :rtype: str
        """
        return self._pool_name

    @pool_name.setter
    def pool_name(self, pool_name):
        """Sets the pool_name of this UpdateVolumeStatReq.


        :param pool_name: The pool_name of this UpdateVolumeStatReq.  # noqa: E501
        :type: str
        """

        self._pool_name = pool_name

    @property
    def stat(self):
        """Gets the stat of this UpdateVolumeStatReq.  # noqa: E501


        :return: The stat of this UpdateVolumeStatReq.  # noqa: E501
        :rtype: VolumeStat
        """
        return self._stat

    @stat.setter
    def stat(self, stat):
        """Sets the stat of this UpdateVolumeStatReq.


        :param stat: The stat of this UpdateVolumeStatReq.  # noqa: E501
        :type: VolumeStat
        """

        self._stat = stat

    @property
    def volume_name(self):
        """Gets the volume_name of this UpdateVolumeStatReq.  # noqa: E501


        :return: The volume_name of this UpdateVolumeStatReq.  # noqa: E501
        :rtype: str
        """
        return self._volume_name

    @volume_name.setter
    def volume_name(self, volume_name):
        """Sets the volume_name of this UpdateVolumeStatReq.


        :param volume_name: The volume_name of this UpdateVolumeStatReq.  # noqa: E501
        :type: str
        """

        self._volume_name = volume_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateVolumeStatReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
